/*
ALEX VERZEA
260324472
COMP310
Mini-Assignment 3
*/ 

#include<stdio.h>
#include<string.h>
#include<stdlib.h>
#include<math.h>
#define MAX 10 /* MAX is the maximum number of processes, 10. */

/*
This program implements the bankers' algorithm, with N processes and 4 resource types, where N is randomly picked between 5 and 10. At the beginning, each process declares the number of each resource types it needs. That is, each process declares its maximum resource requirement, which is a number generated between 5 and 12. The available number of resources for each type is generated by summing the requirements and multiplying the sum by 0.6. Any fractions are rounded up to create the initial reserves for each resource type. A request could be rejected because it invalid (that is the process is requesting more than the max) or it is unsafe to allocate the request. At the end, the program will printout, if the allocation is safe, the allocation matrix and terminate.
*/

/* Compile using gcc bankers_algorithm.c -lm -o bankers_algorithm */
/* Number of processes, maxneed values & allocation values are randomly generated. */

struct process
{
 char pid[4];
 int maxneed[4];
 int allocated[4];
 int need[4];
 int finished;
}p[MAX];

int available[4];
char isSafeProcess[10][4];
void bankers_algorithm(int);

void main()
{
 int n,i,j;
 int res[4];

 srand(time(NULL)); /*This guarantees that the rand() command will truly generate a random value.*/
 n = 5 + rand()%6;
 printf("Processes = %d\n",n);
 for(i=0;i<n;i++)
 {
  memset(p[i].pid, '\0', 4);  /*Initialize the pid of the process. */
  sprintf(p[i].pid,"%d",i);
  printf("pid = %s\n",p[i].pid);
  p[i].maxneed[0] = 5 + rand()%8; /* Maxneed by each process. */
  p[i].maxneed[1] = 5 + rand()%8;
  p[i].maxneed[2] = 5 + rand()%8;
  p[i].maxneed[3] = 5 + rand()%8;
  printf("Maxneed               \t%d \t%d \t%d \t%d\n",p[i].maxneed[0],p[i].maxneed[1],p[i].maxneed[2],p[i].maxneed[3]);
  p[i].allocated[0] = rand()%8; /* Allocation request. */
  p[i].allocated[1] = rand()%8;
  p[i].allocated[2] = rand()%8;
  p[i].allocated[3] = rand()%8;
  printf("Allocation Request    \t%d \t%d \t%d \t%d\n",p[i].allocated[0],p[i].allocated[1],p[i].allocated[2],p[i].allocated[3]);
  
  /* Tests if allocation request is greater than maxneed, in which case, request is invalid and is rejected. */
  if (p[i].allocated[0] > p[i].maxneed[0] || p[i].allocated[1] > p[i].maxneed[1] || 
      p[i].allocated[2] > p[i].maxneed[2] || p[i].allocated[3] > p[i].maxneed[3]) {
      printf("Request rejected because it is invalid. The request is more than the Maxneed.\n");
      exit(0);
  }
  p[i].finished=0;
 }
 for (j = 0; j<4; j++) /* Calculates total amount for each ressource needed. */
  res[j]=0;
 for(i=0;i<n;i++) {
  for (j = 0; j<4; j++)  
    res[j] = res[j] + p[i].maxneed[j]; 
 }
 
 for (j = 0; j<4; j++)
     available[j] = (int)ceil(res[j]*0.6); /* Available Ressource: Roundup using ceiling function from math.h. */
 
printf("\nRessource Available = \t%d \t%d \t%d \t%d\n", available[0],available[1],available[2],available[3]);
   
 bankers_algorithm(n);

}

void bankers_algorithm(int n) /* Bankers' Algorithm in C. */
{
  int i,k=0;
  int j=0,m;
  int amount=0;
  m=n*n;
  
  for(i=0;i<n;i++)
  {
   p[i].need[0]=p[i].maxneed[0]-p[i].allocated[0];
   p[i].need[1]=p[i].maxneed[1]-p[i].allocated[1];
   p[i].need[2]=p[i].maxneed[2]-p[i].allocated[2];
   p[i].need[3]=p[i].maxneed[3]-p[i].allocated[3];
  }
  while(k<=m)
  {
    for(i=0;i<n;i++)
    {
     if(p[i].finished!=1 && p[i].need[0]<=available[0] && p[i].need[1]<=available[1] && p[i].need[2]<=available[2] && p[i].need[3]<=available[3])
     {
     strcpy(isSafeProcess[j],p[i].pid);
     j++;
     amount++;
     p[i].finished=1;
     available[0]+=p[i].allocated[0];
     available[1]+=p[i].allocated[1];
     available[2]+=p[i].allocated[2];
     available[3]+=p[i].allocated[3];
     }
    else
     {
      continue;
     }
    }
   k++;
  }
  if(amount==n)
   {
    printf("\nThe state is safe.\n");
    printf("Allocation Matrix:\n");
    printf("Processes: \tResources:\n");  
    for(i=0;i<n;i++)
    {
     printf("%s \t\t%d\t%d\t%d\t%d \n",isSafeProcess[i],p[i].allocated[0],p[i].allocated[1],p[i].allocated[2],p[i].allocated[3]);
    }
    printf("\n");
   }
   else
   {
    printf("\n\t!Deadlock!");
   }
} 
